# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - run: |
          npm i react react-dom react-script create-react-app webpack
      - uses: actions/upload-artifact@v4
        name: "Upload Node Modules - v4"
        with:
          name: node_modules-v4
          path: node_modules
      - uses: actions/upload-artifact@v3
        name: "Upload Node Modules - v3"
        with:
          name: node_modules-v3
          path: node_modules
      - uses: actions/download-artifact@v4
        name: "Download Node Modules - v4"
        with:
          name: node_modules-v4
          path: node_modules-v4
      - uses: actions/download-artifact@v3
        name: "Download Node Modules - v3"
        with:
          name: node_modules-v3
          path: node_modules-v3
  big-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          dd if=/dev/urandom of=1gb-random bs=1M count=1000
      - uses: actions/upload-artifact@v4
        name: "Upload 1GB - v4"
        with:
          name: 1gb-v4
          path: 1gb-random
          compression-level: 0
      - uses: actions/upload-artifact@v3
        name: "Upload 1GB - v3"
        with:
          name: 1gb-v3
          path: 1gb-random
      - uses: actions/download-artifact@v4
        name: "Download 1GB - v4"
        with:
          name: 1gb-v4
          path: 1gb-v4
      - uses: actions/download-artifact@v3
        name: "Download 1GB - v3"
        with:
          name: 1gb-v3
          path: 1gb-v3
